
using System.Collections.Generic;

public class ObjectsTranslator 
{
    public Dictionary<string, string> ObjectsRusNames { get; private set; } = new Dictionary<string, string>();
	public ObjectsTranslator()
	{
		ObjectsRusNames.Add("f_152", "Отсутствуют рукавицы");
        ObjectsRusNames.Add("f_156", "Отсутствует самоспасатель");
        ObjectsRusNames.Add("f_143", "Отсутствует аптечка");
        ObjectsRusNames.Add("f_145", "Отсутсвутет журнал технического состояния");
        ObjectsRusNames.Add("f_78", "Отсутствует лом");
        ObjectsRusNames.Add("f_28", "Отсутствие молотка между купе 6 и 7");
        ObjectsRusNames.Add("f_27", "Отсутствие молотка между купе 2 и 3");
        ObjectsRusNames.Add("f_54_1", "Отсутствует огнетушитель углекислотный");
        ObjectsRusNames.Add("f_171", "Отсутствует огнетушитель водоэмульсионный");
        ObjectsRusNames.Add("f_188", "Отсутствует освежитель воздуха");
        ObjectsRusNames.Add("f_149", "Отсутствуют очки");
        ObjectsRusNames.Add("f_179", "Отсутствует туалетная бумага");
        ObjectsRusNames.Add("f_134", "Отсутствие постельных принадлежностей внизу");
        ObjectsRusNames.Add("f_134_1", "Отсутствие постельных принадлежностей сверху");
        ObjectsRusNames.Add("f_189", "Присутствует загрязнение в сливе");
        ObjectsRusNames.Add("f_71", "Неисправно крепление дверки зольника");
        ObjectsRusNames.Add("f_72", "Присутствует загрязнение в котле");
        ObjectsRusNames.Add("f_85", "Отсутствует совок");
        ObjectsRusNames.Add("f_191", "Трещина на раковине");
        ObjectsRusNames.Add("f_180", "Отсутствует вставка на унитаз");
        ObjectsRusNames.Add("f_186", "Присутствует течь крана"); 
        ObjectsRusNames.Add("f_67", "Отсутствует пломба на стоп кране    ");
        ObjectsRusNames.Add("f_65", "Рукав не скручен на бобину");
        ObjectsRusNames.Add("f_45", "Отсутствует пломба на стоп кране  ");
        ObjectsRusNames.Add("f_23", "Сломано крепление канатов между купе 2 и 3");
        ObjectsRusNames.Add("f_24", "Сломано крепление канатов между купе 6 и 7");
        ObjectsRusNames.Add("f_178", "Отсутствует металический вкладыш для мусора");
        ObjectsRusNames.Add("f_168", "Отсутствует зеркало");
        ObjectsRusNames.Add("f_54", "Не греется кипятильник (термопот) ");
        ObjectsRusNames.Add("f_214", "Отсутствует киянка");
        ObjectsRusNames.Add("f_150", "Отсутствуют подстаканники");
        ObjectsRusNames.Add("f_84", "Отсутствует резак");
        ObjectsRusNames.Add("f_159", "Отсутствуют средства для уборки");
        ObjectsRusNames.Add("f_160", "Отсутствуют стаканы");
        ObjectsRusNames.Add("f_161", "Отсутствуют столовые приборы");
        ObjectsRusNames.Add("f_162", "Отсутствуют тарелки");
        ObjectsRusNames.Add("f_87", "Отсутствует пломба на лестнице");
        ObjectsRusNames.Add("f_57", "Отсутствие пломбы огнетушителя ");
        ObjectsRusNames.Add("f_58", "Отсутствие чеки огнетушителя ");
        ObjectsRusNames.Add("f_70", "Присутствует загрязнение в зольнике");
        ObjectsRusNames.Add("f_73", "Неисправно крепление дверки котла");
        ObjectsRusNames.Add("f_80", "Отсутствие металлического скребка");
        ObjectsRusNames.Add("f_146", "Порвана страница журнала ТС");
        ObjectsRusNames.Add("f_144", "Отсутствует пломба аптечки");
        ObjectsRusNames.Add("f_173", "Отсутствие чеки огнетушителя водоэмульсионного огнетушителя");
        ObjectsRusNames.Add("f_172", "Отсутствие пломбы огнетушителя водоэмульсионного огнетушителя");
        ObjectsRusNames.Add("f_190", "Отсутствуют бумажные полотенца");
        ObjectsRusNames.Add("f_239", "Не закрыт ящик для угля");
        ObjectsRusNames.Add("f_219", "Отсутствует пломба на стоп кране ");
        ObjectsRusNames.Add("f_238", "Недостаточное количество угля");
        ObjectsRusNames.Add("f_237", "Отсутствует пломба на стоп кране");
        ObjectsRusNames.Add("f_92", "Присутствуют посторонние предметы на тележке");
        ObjectsRusNames.Add("f_59", "Отсутствует раструб огнетушителя");
        ObjectsRusNames.Add("f_185", "Сломан кран");
        ObjectsRusNames.Add("f_26", "Отсутствуют болты крепления каната между купе 6 и 7");
        ObjectsRusNames.Add("f_25", "Отсутствуют болты крепления каната между купе 2 и 3");
        ObjectsRusNames.Add("f_165", "Шкворень не закрыт крышкой");
        ObjectsRusNames.Add("f_229", "Неисправно крепление на мостике");
        ObjectsRusNames.Add("f_47", "Загрязнен ящик для хранения белья ");
        ObjectsRusNames.Add("f_122", "Шкворень не закрыт крышкой ");
        ObjectsRusNames.Add("f_127", "Оборваны нити нижней газетницы");
        ObjectsRusNames.Add("f_128", "Оборваны нити верхней газетницы");
        ObjectsRusNames.Add("f_246", "Оборваны нити газетницы места 5");
        ObjectsRusNames.Add("f_247", "Оборваны нити газетницы места 6");
        ObjectsRusNames.Add("f_248", "Оборваны нити газетницы места 7");
        ObjectsRusNames.Add("f_249", "Оборваны нити газетницы места 8");            
        ObjectsRusNames.Add("f_102", "Оборваны нити газетницы места 33");
        ObjectsRusNames.Add("f_103", "Оборваны нити газетницы места 34");
        ObjectsRusNames.Add("f_104", "Оборваны нити газетницы места 35");
        ObjectsRusNames.Add("f_105", "Оборваны нити газетницы места 36");
        ObjectsRusNames.Add("f_95", "Не закрыт ящик");
        ObjectsRusNames.Add("f_215", "Отсутствует метелка");
        ObjectsRusNames.Add("f_209", "Отсутствует деревянный скребок");
        ObjectsRusNames.Add("f_258", "Отсутствуют постельные принадлежности места 8");
        ObjectsRusNames.Add("f_258_1", "Отсутствуют постельные принадлежности места 7");
        ObjectsRusNames.Add("f_258_2", "Отсутствуют постельные принадлежности места 6");
        ObjectsRusNames.Add("f_258_3", "Отсутствуют постельные принадлежности места 5");
        ObjectsRusNames.Add("f_114", "Отсутствуют постельные принадлежности места 33");
        ObjectsRusNames.Add("f_114_1", "Отсутствуют постельные принадлежности места 34");
        ObjectsRusNames.Add("f_114_2", "Отсутствуют постельные принадлежности места 35");
        ObjectsRusNames.Add("f_114_3", "Отсутствуют постельные принадлежности места 36");
        ObjectsRusNames.Add("f_174", "поврежден шланг водоэмульсионного огнетушителя");
        ObjectsRusNames.Add("c_socketkoridor_k", "Не закреплена розетка");
        ObjectsRusNames.Add("c_socketcoupesleep_kpo", "Не закреплена розетка ");
        ObjectsRusNames.Add("c_socketcoupeofficial_kps", "Не закреплена розетка  ");
        ObjectsRusNames.Add("c_socketcoupenumber2_tp2", "Не закреплена розетка   ");
        ObjectsRusNames.Add("c_socketcoupenumber9_tp9", "Не закреплена розетка    ");
        ObjectsRusNames.Add("c_socketkoridor_mk", "Не закреплена розетка     ");
        ObjectsRusNames.Add("c_socketwc1_wc1", "Не закреплена розетка      ");
        ObjectsRusNames.Add("c_socketwc2_wc2", "Не закреплена розетка       ");
        ObjectsRusNames.Add("c_fastenerscoupesleep_kpo", "Сломан держатель полки");
        ObjectsRusNames.Add("c_fastenerscoupenumber2_tp2", "Сломан держатель полки ");
        ObjectsRusNames.Add("c_fastenerscoupenumber9_tp9", "Сломан держатель полки  ");
        ObjectsRusNames.Add("c_tablecoupenumber2_tp2", "Неисправно крепление столика");
        ObjectsRusNames.Add("c_tablecoupenumber9_tp9", "Неисправно крепление столика ");
        ObjectsRusNames.Add("c_gazetnitsacoupesleep_kpo", "Неисправно крепление газетницы");
        ObjectsRusNames.Add("c_gazetnitsacoupenumber2_tp2", "Неисправно крепление газетницы ");
        ObjectsRusNames.Add("c_gazetnitsacoupenumber9_tp9", "Неисправно крепление газетницы  ");
        ObjectsRusNames.Add("c_inventorydoor_tn", "Ящик для инвентаря не закрыт");
        ObjectsRusNames.Add("c_to2_to3_vs", "Отсутствие трафарета (ТО2, ТО3)");
        ObjectsRusNames.Add("c_ladderoutside_vs", "Излом лестницы");
        ObjectsRusNames.Add("c_handleroutside_vs", "Излом ручек");
        ObjectsRusNames.Add("c_tornfirehose_kk", "Порван рукав");
        ObjectsRusNames.Add("c_datefire_kk", "Просрочен огнетушитель");
        ObjectsRusNames.Add("c_date_to_vs", "Несоответствие даты на трафарете(ТО2, ТО3)");
        ObjectsRusNames.Add("c_povodok_k", "Поводок расхожен");
        ObjectsRusNames.Add("c_brokenlamp_tn", "Неисправна лампа");
        ObjectsRusNames.Add("c_garbagewc_wc2", "Отсутствует мусорный пакет");
        ObjectsRusNames.Add("c_garbagewc_wc1", "Отсутствует мусорный пакет ");
        ObjectsRusNames.Add("c_fresherwc2_wc2", "Отсутствует освежитель воздуха ");
        ObjectsRusNames.Add("c_toiletpapperwc2_wc2", "Отсутствует туалетная бумага ");
        ObjectsRusNames.Add("c_rubbishwc2_wc2", "Присутствует загрязнение в сливе ");
        ObjectsRusNames.Add("c_crackwc2_wc2", "Трещина на раковине ");
        ObjectsRusNames.Add("c_insertpaperwc2_wc2", "Отсутствуют вставки на унитаз ");
        ObjectsRusNames.Add("c_paddlewc2_wc2", "Присутствует течь крана ");
        ObjectsRusNames.Add("c_toilettovelwc2_wc2", "Отсутствуют бумажные полотенца ");
        ObjectsRusNames.Add("c_wctap2_wc2", "Сломан кран ");
        ObjectsRusNames.Add("c_brokenrastryb_kk", "Неисправен раструб");
        ObjectsRusNames.Add("c_selfhelperdate_kps", "Несоответствие срока годности самоспасателя");
        ObjectsRusNames.Add("c_selfhelperbroken_kps", "Нарушена упаковка самоспасателя");
        ObjectsRusNames.Add("c_firstaidkitdate_kps", "Просрочена аптечка");
        ObjectsRusNames.Add("c_fireextinguisherwaterdate_mk", "Просрочен водоэмульсионный огнетушитель");
        ObjectsRusNames.Add("c_fireextinguishersourtype_kk", "Несоответствие типа огнетушителя");
        ObjectsRusNames.Add("c_fireextinguisherwatertype_mk", "Несоответствие типа огнетушителя ");
        ObjectsRusNames.Add("c_handlehorizontalwc1_wc1", "Ненадежное крепление ручки");
        ObjectsRusNames.Add("c_secretkeyoff_tn", "Секретка не поворачивается");
        ObjectsRusNames.Add("c_flushbutton1_wc1", "Кнопка смыва не работает");
        ObjectsRusNames.Add("c_flushbutton2_wc2", "Кнопка смыва не работает ");
        ObjectsRusNames.Add("c_tapwater1_wc1", "Отсутствует вода в кране");
        ObjectsRusNames.Add("c_tapwater2_wc2", "Отсутствует вода в кране ");
        ObjectsRusNames.Add("c_fireextinguisherbrokenhose_mk", "Не прикручен шланг огнетушителя");
        ObjectsRusNames.Add("c_handlevertical_tp2", "Ненадежное крепление ручки ");
        ObjectsRusNames.Add("c_blindsfastening_k", "Неисправно крепление автошторы");
        ObjectsRusNames.Add("c_blindsnonfixed_k", "Автоштора не фиксируется");
        ObjectsRusNames.Add("c_specialkey_tr", "Не поворачивается спецключ");
        ObjectsRusNames.Add("c_underwearbroken_k", "Ящик для белья не закрыт");
        ObjectsRusNames.Add("c_ladder_tp2", "Сломана лестница");
        ObjectsRusNames.Add("c_treescraper_ko", "Металлический скребок не закреплен на рукоятке");
        ObjectsRusNames.Add("c_3grannyykey_tr", "Не поворачивается трехгранный ключ");
        ObjectsRusNames.Add("c_kotelflow_ko", "Течет котел");
        ObjectsRusNames.Add("c_nasosflow_ko", "Течет насос");
        ObjectsRusNames.Add("c_paddlekran_ko", "Течет кран");
        ObjectsRusNames.Add("c_brokennasos_ko", "Сломан насос");
        ObjectsRusNames.Add("c_brokenkran_ko", "Не поворачивается кран");
        ObjectsRusNames.Add("c_pumpingwater_ko", "Отсутствует вода в котле");
        ObjectsRusNames.Add("c_touchscreen_kps", "Не включается сенсорная панель");
        ObjectsRusNames.Add("c_table_nonfix_kpo", "Не фиксируется столик");
        ObjectsRusNames.Add("c_tablecoupesleep_kpo", "Неисправно крепление столика  ");
        ObjectsRusNames.Add("c_table_nonfix_tp2", "Не фиксируется столик ");
        ObjectsRusNames.Add("c_table_nonfix_tp9", "Не фиксируется столик  ");
        ObjectsRusNames.Add("c_stop_number_k", "Неправильный номер предприятия");
        ObjectsRusNames.Add("c_falsenumber_tr", "Неправильный номер предприятия ");
        ObjectsRusNames.Add("c_stop_number_kk", "Неправильный номер предприятия  ");
        ObjectsRusNames.Add("c_falsenum_tn", "Неправильный номер предприятия   ");
        ObjectsRusNames.Add("c_temperature_filtr_kk", "Грязный фильтр");
        ObjectsRusNames.Add("c_temperature_nowater_kk", "Отсутствует вода");
        ObjectsRusNames.Add("c_temperature_waternogo_kk", "Не поступает вода");
        ObjectsRusNames.Add("c_blindsnonfixed_tp9", "Автоштора не фиксируется ");
        ObjectsRusNames.Add("c_blindsnonfixed_tp2", "Автоштора не фиксируется  ");
        ObjectsRusNames.Add("c_blindsnonfixed_kpo", "Автоштора не фиксируется   ");
        ObjectsRusNames.Add("c_blindsnonfixed_kps", "Автоштора не фиксируется    ");
        ObjectsRusNames.Add("c_blindsfastening_kps", "Неисправно крепление автошторы ");
        ObjectsRusNames.Add("c_blindsfastening_kpo", "Неисправно крепление автошторы  ");
        ObjectsRusNames.Add("c_blindsfastening_tp2", "Неисправно крепление автошторы   ");
        ObjectsRusNames.Add("c_blindsfastening_tp9", "Неисправно крепление автошторы    ");
        ObjectsRusNames.Add("c_ladder_tp9", "Сломана лестница ");
        ObjectsRusNames.Add("c_ladder_kpo", "Сломана лестница  ");
        ObjectsRusNames.Add("c_inventorydoor_off_tn", "Отсутствие инвентаря");
        ObjectsRusNames.Add("c_o_syspojar_falsework_kps", "Ложно срабатывает система ПБ");
        ObjectsRusNames.Add("c_o_syspojar_offready_kps", "Не включается лампочка - Готов");
        ObjectsRusNames.Add("c_tumblerbroken_kps", "Излом тумблера сенсорной панели");
        ObjectsRusNames.Add("c_underwearbrokenizlom_k", "Сломаны петли ящика для белья");





        ObjectsRusNames.Add("Kotel", "Котловое отделение");
        ObjectsRusNames.Add("VestibuleWorking", "Рабочий тамбур");
        ObjectsRusNames.Add("WC", "Санитарный узел");
        ObjectsRusNames.Add("Koridor", "Коридор");
        ObjectsRusNames.Add("SmallKoridor", "Малый коридор");
        ObjectsRusNames.Add("ObliqueKoridor", "Косой коридор");
        ObjectsRusNames.Add("CoupeSleep", "Купе проводника(отдыха)");
        ObjectsRusNames.Add("CoupeOfficial", "Купе проводника(служебное)");     
        ObjectsRusNames.Add("VestibuleNonWorking", "Тамбур нерабочий");
        ObjectsRusNames.Add("WagonOutside", "Вагон снаружи");
        ObjectsRusNames.Add("None", "Выбранные неисправности:");
        ObjectsRusNames.Add("CoupeNumber9", "Купе № 9");
        ObjectsRusNames.Add("CoupeNumber2", "Купе № 2");
        ObjectsRusNames.Add("WC2", "Санитарный узел №2");
    }
}
