
using System.Collections.Generic;

public class ObjectsTranslator 
{
    public Dictionary<string, string> ObjectsRusNames { get; private set; } = new Dictionary<string, string>();
	public ObjectsTranslator()
	{
		ObjectsRusNames.Add("c_gloves_kps", "Отсутствуют рукавицы");
        ObjectsRusNames.Add("c_selfhelper_kps", "Отсутствует самоспасатель");
        ObjectsRusNames.Add("c_firstaidkit_kps", "Отсутствует аптечка");
        ObjectsRusNames.Add("c_journaloff_kps", "Отсутсвутет журнал технического состояния");
        ObjectsRusNames.Add("c_lom_ko", "Отсутствует лом");
        ObjectsRusNames.Add("c_nohammer_k", "Отсутствует молоток");
        ObjectsRusNames.Add("c_fireextinguishersour_kk", "Отсутствует огнетушитель углекислотный");
        ObjectsRusNames.Add("c_fireextinguisherwater_mk", "Отсутствует огнетушитель водоэмульсионный");
        ObjectsRusNames.Add("c_fresherwc1_wc1", "Отсутствует освежитель воздуха");
        ObjectsRusNames.Add("c_glasses_kps", "Отсутствуют очки");
        ObjectsRusNames.Add("c_toiletpapperwc1_wc1", "Отсутствует туалетная бумага");
        ObjectsRusNames.Add("c_bedstuff_kpo", "Отсутствуют постельные принадлежности");
        ObjectsRusNames.Add("c_rubbishwc1_wc1", "Присутствует загрязнение в сливе");
        ObjectsRusNames.Add("c_zolnik_ko", "Неисправно крепление дверки зольника");
        ObjectsRusNames.Add("c_kotel_ko", "Присутствует загрязнение в котле");
        ObjectsRusNames.Add("c_sovok_ko", "Отсутствует совок");
        ObjectsRusNames.Add("c_crackwc1_wc1", "Трещина на раковине");
        ObjectsRusNames.Add("c_insertpaperwc1_wc1", "Отсутствуют вставки на унитаз");
        ObjectsRusNames.Add("c_paddlewc1_wc1", "Присутствует течь крана"); 
        ObjectsRusNames.Add("c_plomba_kk", "Отсутствует пломба на стоп кране    ");
        ObjectsRusNames.Add("c_firehose_kk", "Рукав не скручен на бобину");
        ObjectsRusNames.Add("c_plomba_k", "Отсутствует пломба на стоп кране  ");
        ObjectsRusNames.Add("c_fracture_k", "Сломано крепление для каната");
        ObjectsRusNames.Add("c_garbagebag_mk", "Отсутствует металический вкладыш для мусора");
        ObjectsRusNames.Add("c_mirror_mk", "Отсутствует зеркало");
        ObjectsRusNames.Add("c_temperature_kk", "Не греется кипятильник (термопот) ");
        ObjectsRusNames.Add("c_mallet_off_tn", "Отсутствует киянка");
        ObjectsRusNames.Add("c_halfglass_kps", "Отсутствуют подстаканники");
        ObjectsRusNames.Add("c_cutter_ko", "Отсутствует резак");
        ObjectsRusNames.Add("c_cleaningstuff_kps", "Отсутствуют средства для уборки");
        ObjectsRusNames.Add("c_cup_kps", "Отсутствуют стаканы");
        ObjectsRusNames.Add("c_eatingstuffoff_kps", "Отсутствуют столовые приборы");
        ObjectsRusNames.Add("c_plate_kps", "Отсутствуют тарелки");
        ObjectsRusNames.Add("c_stairsplomba_vs", "Отсутствует пломба на лестнице");
        ObjectsRusNames.Add("c_plombaobliquekoridor_kk", "Отсутствие пломбы огнетушителя ");
        ObjectsRusNames.Add("c_chekaobliquekoridor_kk", "Отсутствие чеки огнетушителя ");
        ObjectsRusNames.Add("c_zolnikdirt_ko", "Присутствует загрязнение в зольнике");
        ObjectsRusNames.Add("c_koteldoor_ko", "Неисправно крепление дверки котла");
        ObjectsRusNames.Add("c_scraper_ko", "Отсутствует скребок ");
        ObjectsRusNames.Add("c_pages_kps", "Порвана страница журнала ТС");
        ObjectsRusNames.Add("c_plombamedkit_kps", "Отсутствует пломба аптечки");
        ObjectsRusNames.Add("c_chekasmallkoridor_mk", "Отсутствие чеки огнетушителя");
        ObjectsRusNames.Add("c_plombasmallkorido_mk", "Отсутствие пломбы огнетушителя");
        ObjectsRusNames.Add("c_toilettovelwc1_wc1", "Отсутствуют бумажные полотенца");
        ObjectsRusNames.Add("c_coalbox_tr", "Не закрыт ящик для угля");
        ObjectsRusNames.Add("c_plombavestibulenonworking_tn", "Отсутствует пломба на стоп кране ");
        ObjectsRusNames.Add("c_coal_off_tr", "Недостаточное количество угля");
        ObjectsRusNames.Add("c_plomba_tr", "Отсутствует пломба на стоп кране");
        ObjectsRusNames.Add("c_hammeroutside_vs", "Присутствуют посторонние предметы на тележке");
        ObjectsRusNames.Add("c_rastryb_kk", "Отсутствует раструб огнетушителя");
        ObjectsRusNames.Add("c_wctap1_wc1", "Сломан кран");
        ObjectsRusNames.Add("c_nofastening_k", "Отсутствуют болты крепления каната");
        ObjectsRusNames.Add("c_shkvorencoupeofficial_kps", "Шкворень не закрыт крышкой");
        ObjectsRusNames.Add("c_bridge_tr", "Неисправно крепление на мостике");
        ObjectsRusNames.Add("c_musorkoridor_k", "Загрязнен ящик для хранения белья ");
        ObjectsRusNames.Add("c_shkvorencoupe9_tp9", "Шкворень не закрыт крышкой ");
        ObjectsRusNames.Add("c_gazetnitsa_kpo", "Оборваны нити газетницы");
        ObjectsRusNames.Add("c_tipovoecoupegazet_tp2", "Оборваны нити газетницы ");
        ObjectsRusNames.Add("c_coupe9gazet_tp9", "Оборваны нити газетницы  ");
        ObjectsRusNames.Add("c_outsidenoclosebox_vs", "Не закрыт ящик");
        ObjectsRusNames.Add("c_metla_off_tn", "Отсутствует метелка");
        ObjectsRusNames.Add("c_scraper_off_tn", "Отсутствует скребок");
        ObjectsRusNames.Add("c_bedstuffcoupe2_tp2", "Отсутствуют постельные принадлежности ");
        ObjectsRusNames.Add("c_bedstuffcoupe9_tp9", "Отсутствуют постельные принадлежности  ");
        ObjectsRusNames.Add("c_fireextinguisherhose_mk", "поврежден шланг огнетушителя");
        ObjectsRusNames.Add("c_socketkoridor_k", "Не закреплена розетка");
        ObjectsRusNames.Add("c_socketcoupesleep_kpo", "Не закреплена розетка ");
        ObjectsRusNames.Add("c_socketcoupeofficial_kps", "Не закреплена розетка  ");
        ObjectsRusNames.Add("c_socketcoupenumber2_tp2", "Не закреплена розетка   ");
        ObjectsRusNames.Add("c_socketcoupenumber9_tp9", "Не закреплена розетка    ");
        ObjectsRusNames.Add("c_socketkoridor_mk", "Не закреплена розетка     ");
        ObjectsRusNames.Add("c_socketwc1_wc1", "Не закреплена розетка      ");
        ObjectsRusNames.Add("c_socketwc2_wc2", "Не закреплена розетка       ");
        ObjectsRusNames.Add("c_fastenerscoupesleep_kpo", "Сломан держатель полки");
        ObjectsRusNames.Add("c_fastenerscoupenumber2_tp2", "Сломан держатель полки ");
        ObjectsRusNames.Add("c_fastenerscoupenumber9_tp9", "Сломан держатель полки  ");
        ObjectsRusNames.Add("c_tablecoupenumber2_tp2", "Неисправно крепление столика");
        ObjectsRusNames.Add("c_tablecoupenumber9_tp9", "Неисправно крепление столика ");
        ObjectsRusNames.Add("c_gazetnitsacoupesleep_kpo", "Неисправно крепление газетницы");
        ObjectsRusNames.Add("c_gazetnitsacoupenumber2_tp2", "Неисправно крепление газетницы ");
        ObjectsRusNames.Add("c_gazetnitsacoupenumber9_tp9", "Неисправно крепление газетницы  ");
        ObjectsRusNames.Add("c_inventorydoor_tn", "Ящик для инвентаря не закрыт");
        ObjectsRusNames.Add("c_to2_to3_vs", "Отсутствие трафарета (ТО2, ТО3)");
        ObjectsRusNames.Add("c_ladderoutside_vs", "Излом лестницы");
        ObjectsRusNames.Add("c_handleroutside_vs", "Излом ручек");
        ObjectsRusNames.Add("c_tornfirehose_kk", "Порван рукав");
        ObjectsRusNames.Add("c_datefire_kk", "Просрочен огнетушитель");
        ObjectsRusNames.Add("c_date_to_vs", "Несоответствие даты на трафарете(ТО2, ТО3)");
        ObjectsRusNames.Add("c_povodok_k", "Поводок расхожен");
        ObjectsRusNames.Add("c_brokenlamp_tn", "Неисправна лампа");
        ObjectsRusNames.Add("c_garbagewc_wc2", "Отсутствует мусорный пакет");
        ObjectsRusNames.Add("c_garbagewc_wc1", "Отсутствует мусорный пакет ");
        ObjectsRusNames.Add("c_fresherwc2_wc2", "Отсутствует освежитель воздуха ");
        ObjectsRusNames.Add("c_toiletpapperwc2_wc2", "Отсутствует туалетная бумага ");
        ObjectsRusNames.Add("c_rubbishwc2_wc2", "Присутствует загрязнение в сливе ");
        ObjectsRusNames.Add("c_crackwc2_wc2", "Трещина на раковине ");
        ObjectsRusNames.Add("c_insertpaperwc2_wc2", "Отсутствуют вставки на унитаз ");
        ObjectsRusNames.Add("c_paddlewc2_wc2", "Присутствует течь крана ");
        ObjectsRusNames.Add("c_toilettovelwc2_wc2", "Отсутствуют бумажные полотенца ");
        ObjectsRusNames.Add("c_wctap2_wc2", "Сломан кран ");
        ObjectsRusNames.Add("c_brokenrastryb_kk", "Неисправен раструб");
        ObjectsRusNames.Add("c_selfhelperdate_kps", "Несоответствие срока годности самоспасателя");
        ObjectsRusNames.Add("c_selfhelperbroken_kps", "Нарушена упаковка самоспасателя");
        ObjectsRusNames.Add("c_firstaidkitdate_kps", "Просрочена аптечка");
        ObjectsRusNames.Add("c_fireextinguisherwaterdate_mk", "Просрочен водоэмульсионный огнетушитель");
        ObjectsRusNames.Add("c_fireextinguishersourtype_kk", "Несоответствие типа огнетушителя");
        ObjectsRusNames.Add("c_fireextinguisherwatertype_mk", "Несоответствие типа огнетушителя ");
        ObjectsRusNames.Add("c_handlehorizontalwc1_wc1", "Ненадежное крепление ручки");
        ObjectsRusNames.Add("c_secretkeyoff_tn", "Секретка не поворачивается");
        ObjectsRusNames.Add("c_flushbutton1_wc1", "Кнопка смыва не работает");
        ObjectsRusNames.Add("c_flushbutton2_wc2", "Кнопка смыва не работает ");
        ObjectsRusNames.Add("c_tapwater1_wc1", "Отсутствует вода в кране");
        ObjectsRusNames.Add("c_tapwater2_wc2", "Отсутствует вода в кране ");
        ObjectsRusNames.Add("c_fireextinguisherbrokenhose_mk", "Не прикручен шланг огнетушителя");
        ObjectsRusNames.Add("c_handlevertical_tp2", "Ненадежное крепление ручки ");
        ObjectsRusNames.Add("c_blindsfastening_k", "Неисправно крепление автошторы");
        ObjectsRusNames.Add("c_blindsnonfixed_k", "Автоштора не фиксируется");
        ObjectsRusNames.Add("c_specialkey_tr", "Не поворачивается спецключ");
        ObjectsRusNames.Add("c_underwearbroken_k", "Ящик для белья не закрыт");
        ObjectsRusNames.Add("c_ladder_tp2", "Сломана лестница");
        ObjectsRusNames.Add("c_treescraper_ko", "Металлический скребок не закреплен на рукоятке");
        ObjectsRusNames.Add("c_3grannyykey_tr", "Не поворачивается трехгранный ключ");
        ObjectsRusNames.Add("c_kotelflow_ko", "Течет котел");
        ObjectsRusNames.Add("c_nasosflow_ko", "Течет насос");
        ObjectsRusNames.Add("c_paddlekran_ko", "Течет кран");
        ObjectsRusNames.Add("c_brokennasos_ko", "Сломан насос");
        ObjectsRusNames.Add("c_brokenkran_ko", "Не поворачивается кран");
        ObjectsRusNames.Add("c_pumpingwater_ko", "Отсутствует вода в котле");
        ObjectsRusNames.Add("c_touchscreen_kps", "Не включается сенсорная панель");
        ObjectsRusNames.Add("c_table_nonfix_kpo", "Не фиксируется столик");
        ObjectsRusNames.Add("c_tablecoupesleep_kpo", "Неисправно крепление столика  ");
        ObjectsRusNames.Add("c_table_nonfix_tp2", "Не фиксируется столик ");
        ObjectsRusNames.Add("c_table_nonfix_tp9", "Не фиксируется столик  ");
        ObjectsRusNames.Add("c_stop_number_k", "Неправильный номер предприятия");
        ObjectsRusNames.Add("c_falsenumber_tr", "Неправильный номер предприятия ");
        ObjectsRusNames.Add("c_stop_number_kk", "Неправильный номер предприятия  ");
        ObjectsRusNames.Add("c_falsenum_tn", "Неправильный номер предприятия   ");
        ObjectsRusNames.Add("c_temperature_filtr_kk", "Грязный фильтр");
        ObjectsRusNames.Add("c_temperature_nowater_kk", "Отсутствует вода");
        ObjectsRusNames.Add("c_temperature_waternogo_kk", "Не поступает вода");
        ObjectsRusNames.Add("c_blindsnonfixed_tp9", "Автоштора не фиксируется ");
        ObjectsRusNames.Add("c_blindsnonfixed_tp2", "Автоштора не фиксируется  ");
        ObjectsRusNames.Add("c_blindsnonfixed_kpo", "Автоштора не фиксируется   ");
        ObjectsRusNames.Add("c_blindsnonfixed_kps", "Автоштора не фиксируется    ");
        ObjectsRusNames.Add("c_blindsfastening_kps", "Неисправно крепление автошторы ");
        ObjectsRusNames.Add("c_blindsfastening_kpo", "Неисправно крепление автошторы  ");
        ObjectsRusNames.Add("c_blindsfastening_tp2", "Неисправно крепление автошторы   ");
        ObjectsRusNames.Add("c_blindsfastening_tp9", "Неисправно крепление автошторы    ");
        ObjectsRusNames.Add("c_ladder_tp9", "Сломана лестница ");
        ObjectsRusNames.Add("c_ladder_kpo", "Сломана лестница  ");
        ObjectsRusNames.Add("c_inventorydoor_off_tn", "Отсутствие инвентаря");
        ObjectsRusNames.Add("c_o_syspojar_falsework_kps", "Ложно срабатывает система ПБ");
        ObjectsRusNames.Add("c_o_syspojar_offready_kps", "Не включается лампочка - Готов");
        ObjectsRusNames.Add("c_tumblerbroken_kps", "Излом тумблера сенсорной панели");
        ObjectsRusNames.Add("c_underwearbrokenizlom_k", "Сломаны петли ящика для белья");





        ObjectsRusNames.Add("Kotel", "Котловое отделение");
        ObjectsRusNames.Add("VestibuleWorking", "Рабочий тамбур");
        ObjectsRusNames.Add("WC", "Санитарный узел");
        ObjectsRusNames.Add("Koridor", "Коридор");
        ObjectsRusNames.Add("SmallKoridor", "Малый коридор");
        ObjectsRusNames.Add("ObliqueKoridor", "Косой коридор");
        ObjectsRusNames.Add("CoupeSleep", "Купе проводника(отдыха)");
        ObjectsRusNames.Add("CoupeOfficial", "Купе проводника(служебное)");     
        ObjectsRusNames.Add("VestibuleNonWorking", "Тамбур нерабочий");
        ObjectsRusNames.Add("WagonOutside", "Вагон снаружи");
        ObjectsRusNames.Add("None", "Выбранные неисправности:");
        ObjectsRusNames.Add("CoupeNumber9", "Купе № 9");
        ObjectsRusNames.Add("CoupeNumber2", "Купе № 2");
        ObjectsRusNames.Add("WC2", "Санитарный узел №2");
    }
}
