
using System.Collections.Generic;

public class ObjectsTranslator 
{
    public Dictionary<string, string> ObjectsRusNames { get; private set; } = new Dictionary<string, string>();
	public ObjectsTranslator()
	{
		ObjectsRusNames.Add("gloves", "Отсутствуют рукавицы");
        ObjectsRusNames.Add("selfHelper", "Отсутствует самоспасатель");
        ObjectsRusNames.Add("firstAidKit", "Отсутствует аптечка");
        ObjectsRusNames.Add("journal", "Отсутсвутет журнал технического состояния");
        ObjectsRusNames.Add("c_lom_ko", "Отсутствует лом");
        ObjectsRusNames.Add("hammer", "Отсутствует молоток");
        ObjectsRusNames.Add("fireExtinguisherSour", "Отсутствует огнетушитель углекислотный");
        ObjectsRusNames.Add("fireExtinguisherWater", "Отсутствует огнетушитель водоэмульсионный");
        ObjectsRusNames.Add("fresher", "Отсутствует освежитель воздуха");
        ObjectsRusNames.Add("glasses", "Отсутствуют очки");
        ObjectsRusNames.Add("toiletPapper", "Отсутствует туалетная бумага");
        ObjectsRusNames.Add("bedStuff", "Отсутствуют постельные принадлежности");
        ObjectsRusNames.Add("rubbish", "Присутствует загрязнение в сливе");
        ObjectsRusNames.Add("c_zolnik_ko", "Неисправно крепление дверки зольника");
        ObjectsRusNames.Add("c_kotel_ko", "Присутствует загрязнение в котле");
        ObjectsRusNames.Add("sovok", "Отсутствует совок");
        ObjectsRusNames.Add("crack", "Трещина на раковине");
        ObjectsRusNames.Add("insertPaper", "Отсутствуют вставки на унитаз");
        ObjectsRusNames.Add("paddle", "Присутствует течь крана"); 
        ObjectsRusNames.Add("plomba", "Отсутствует пломба на стоп кране    ");
        ObjectsRusNames.Add("firehose", "Рукав не скручен на бобину");
        ObjectsRusNames.Add("mainPlomba", "Отсутствует пломба на стоп кране  ");
        ObjectsRusNames.Add("fastening", "Сломано крепление для каната");
        ObjectsRusNames.Add("cheka", "Отсутствие чеки углекислотного огнетушителя");
        ObjectsRusNames.Add("garbageBag", "Отсутствует металический вкладыш для мусора");
        ObjectsRusNames.Add("mirror", "Отсутствует зеркало");
        ObjectsRusNames.Add("temperature", "Не греется кипятильник (термопот) ");
        ObjectsRusNames.Add("c_mallet_off_tn", "Отсутствует киянка");
        ObjectsRusNames.Add("halfGlass", "Отсутствуют подстаканники");
        ObjectsRusNames.Add("cutter", "Отсутствует резак");
        ObjectsRusNames.Add("cleaningStuff", "Отсутствуют средства для уборки");
        ObjectsRusNames.Add("cup", "Отсутствуют стаканы");
        ObjectsRusNames.Add("eatingStuff", "Отсутствуют столовые приборы");
        ObjectsRusNames.Add("plate", "Отсутствуют тарелки");
        ObjectsRusNames.Add("stairsPlomba", "Отсутствует пломба на лестнице");
        ObjectsRusNames.Add("plombaObliqueKoridor", "Отсутствие пломбы огнетушителя ");
        ObjectsRusNames.Add("chekaObliqueKoridor", "Отсутствие чеки огнетушителя ");
        ObjectsRusNames.Add("c_zolnikdirt_ko", "Присутствует загрязнение в зольнике");
        ObjectsRusNames.Add("c_koteldoor_ko", "Неисправно крепление дверки котла");
        ObjectsRusNames.Add("c_scraper_ko", "Отсутствует скребок");
        ObjectsRusNames.Add("pages", "Порвана страница журнала ТС");
        ObjectsRusNames.Add("plombaMedKit", "Отсутствует пломба аптечки");
        ObjectsRusNames.Add("chekaSmallKoridor", "Отсутствие чеки огнетушителя");
        ObjectsRusNames.Add("plombaSmallKoridor", "Отсутствие пломбы огнетушителя");
        ObjectsRusNames.Add("toiletTovel", "Отсутствуют бумажные полотенца");
        ObjectsRusNames.Add("c_coalbox_tr", "Не закрыт ящик для угля");
        ObjectsRusNames.Add("c_plombavestibulenonworking_tn", "Отсутствует пломба на стоп кране ");
        ObjectsRusNames.Add("c_coal_off_tr", "Недостаточное количество угля");
        ObjectsRusNames.Add("c_plomba_tr", "Отсутствует пломба на стоп кране");
        ObjectsRusNames.Add("hammerOutside", "Присутствуют посторонние предметы на тележке");
        ObjectsRusNames.Add("rastryb", "Отсутствует раструб огнетушителя");
        ObjectsRusNames.Add("wcTap", "Сломан кран");
        ObjectsRusNames.Add("fasteningBolt", "Отсутствуют болты крепления каната");
        ObjectsRusNames.Add("shkvorenCoupeOfficial", "Шкворень не закрыт крышкой");
        ObjectsRusNames.Add("c_bridge_tr", "Неисправно крепление на мостике");
        ObjectsRusNames.Add("musorKoridor", "Загрязнен ящик для хранения белья ");
        ObjectsRusNames.Add("shkvorenCoupe9", "Шкворень не закрыт крышкой ");
        ObjectsRusNames.Add("gazetnitsa", "Оборваны нити газетницы");
        ObjectsRusNames.Add("tipovoeCoupeGazet", "Оборваны нити газетницы ");
        ObjectsRusNames.Add("coupe9Gazet", "Оборваны нити газетницы  ");
        ObjectsRusNames.Add("outsideBox", "Не закрыт ящик");
        ObjectsRusNames.Add("c_metla_off_tn", "Отсутствует метелка");
        ObjectsRusNames.Add("c_scraper_off_tn", "Отсутствует скребок");
        ObjectsRusNames.Add("bedStuffCoupe2", "Отсутствуют постельные принадлежности ");
        ObjectsRusNames.Add("bedStuffCoupe9", "Отсутствуют постельные принадлежности  ");
        ObjectsRusNames.Add("fireExtinguisherHose", "поврежден шланг огнетушителя");
        ObjectsRusNames.Add("socketKoridor", "Не закреплена розетка");
        ObjectsRusNames.Add("socketCoupeSleep", "Не закреплена розетка ");
        ObjectsRusNames.Add("socketCoupeOfficial", "Не закреплена розетка  ");
        ObjectsRusNames.Add("socketCoupeNumber2", "Не закреплена розетка   ");
        ObjectsRusNames.Add("socketCoupeNumber9", "Не закреплена розетка    ");
        ObjectsRusNames.Add("socketSmallKoridor", "Не закреплена розетка     ");
        ObjectsRusNames.Add("socketWC", "Не закреплена розетка      ");
        ObjectsRusNames.Add("socketWC2", "Не закреплена розетка       ");
        ObjectsRusNames.Add("fastenersCoupeSleep", "Сломан держатель полки");
        ObjectsRusNames.Add("fastenersCoupeNumber2", "Сломан держатель полки ");
        ObjectsRusNames.Add("fastenersCoupeNumber9", "Сломан держатель полки  ");
        ObjectsRusNames.Add("tableCoupeNumber2", "Неисправно крепление столика");
        ObjectsRusNames.Add("tableCoupeNumber9", "Неисправно крепление столика ");
        ObjectsRusNames.Add("gazetnitsaCoupeSleep", "Неисправно крепление газетницы");
        ObjectsRusNames.Add("gazetnitsaCoupeNumber2", "Неисправно крепление газетницы ");
        ObjectsRusNames.Add("gazetnitsaCoupeNumber9", "Неисправно крепление газетницы  ");
        ObjectsRusNames.Add("c_inventorydoor_tn", "Ящик для инвентаря не закрыт");
        ObjectsRusNames.Add("tO2TO3", "Отсутствие трафарета (ТО2, ТО3)");
        ObjectsRusNames.Add("ladderOutside", "Излом лестницы");
        ObjectsRusNames.Add("handlerOutside", "Излом ручек");
        ObjectsRusNames.Add("tornFireHose", "Порван рукав");
        ObjectsRusNames.Add("dateFire", "Просрочен огнетушитель");
        ObjectsRusNames.Add("dateTO", "Несоответствие даты на трафарете(ТО2, ТО3)");
        ObjectsRusNames.Add("povodok", "Поводок расхожен");
        ObjectsRusNames.Add("c_brokenlamp_tn", "Неисправна лампа");
        ObjectsRusNames.Add("garbageWC2", "Отсутствует мусорный пакет");
        ObjectsRusNames.Add("garbageWC", "Отсутствует мусорный пакет ");
        ObjectsRusNames.Add("fresherWC2", "Отсутствует освежитель воздуха ");
        ObjectsRusNames.Add("toiletPapperWC2", "Отсутствует туалетная бумага ");
        ObjectsRusNames.Add("rubbishWC2", "Присутствует загрязнение в сливе ");
        ObjectsRusNames.Add("crackWC2", "Трещина на раковине ");
        ObjectsRusNames.Add("insertPaperWC2", "Отсутствуют вставки на унитаз ");
        ObjectsRusNames.Add("paddleWC2", "Присутствует течь крана ");
        ObjectsRusNames.Add("toiletTovelWC2", "Отсутствуют бумажные полотенца ");
        ObjectsRusNames.Add("wcTapWC2", "Сломан кран ");
        ObjectsRusNames.Add("brokenRastryb", "Неисправен раструб");
        ObjectsRusNames.Add("selfHelperDate", "Несоответствие срока годности самоспасателя");
        ObjectsRusNames.Add("selfHelperBroken", "Нарушена упаковка самоспасателя");
        ObjectsRusNames.Add("firstAidKitDate", "Просрочена аптечка");
        ObjectsRusNames.Add("fireExtinguisherWaterDate", "Просрочен водоэмульсионный огнетушитель");
        ObjectsRusNames.Add("fireExtinguisherSourType", "Несоответствие типа огнетушителя");
        ObjectsRusNames.Add("fireExtinguisherWaterType", "Несоответствие типа огнетушителя ");
        ObjectsRusNames.Add("c_handlehorizontalwc1_wc1", "Ненадежное крепление ручки");
        ObjectsRusNames.Add("c_secretkeyoff_tn", "Секретка не поворачивается");
        ObjectsRusNames.Add("flushButton", "Кнопка смыва не работает");
        ObjectsRusNames.Add("flushButtonWC2", "Кнопка смыва не работает ");
        ObjectsRusNames.Add("tapWater", "Отсутствует вода в кране");
        ObjectsRusNames.Add("tapWaterWC2", "Отсутствует вода в кране ");
        ObjectsRusNames.Add("fireExtinguisherBrokenHose", "Не прикручен шланг огнетушителя");
        ObjectsRusNames.Add("handleVertical", "Ненадежное крепление ручки ");
        ObjectsRusNames.Add("blindsFastening", "Неисправно крепление автошторы");
        ObjectsRusNames.Add("blindsNonFixed", "Автоштора не фиксируется");
        ObjectsRusNames.Add("c_specialkey_tr", "Не поворачивается спецключ");
        ObjectsRusNames.Add("underwearBroken", "Ящик для белья не закрыт");
        ObjectsRusNames.Add("ladderBroken", "Сломана лестница");
        ObjectsRusNames.Add("c_treescraper_ko", "Металлический скребок не закреплен на рукоятке");
        ObjectsRusNames.Add("c_3grannyykey_tr", "Не поворачивается трехгранный ключ");
        ObjectsRusNames.Add("c_kotelflow_ko", "Течет котел");
        ObjectsRusNames.Add("с_nasosflow_ko", "Течет насос");
        ObjectsRusNames.Add("c_paddlekran_ko", "Течет кран");
        ObjectsRusNames.Add("с_brokennasos_ko", "Сломан насос");
        ObjectsRusNames.Add("c_brokenkran_ko", "Не поворачивается кран");
        ObjectsRusNames.Add("c_pumpingwater_ko", "Отсутствует вода в котле");
        ObjectsRusNames.Add("touchScreen", "Не включается сенсорная панель");
        ObjectsRusNames.Add("noFixedTable", "Не фиксируется столик");
        ObjectsRusNames.Add("tableCoupeSleep", "Неисправно крепление столика  ");
        ObjectsRusNames.Add("noFixedTableCoupe2", "Не фиксируется столик ");
        ObjectsRusNames.Add("noFixedTableCoupe9", "Не фиксируется столик  ");
        ObjectsRusNames.Add("businessNumberKoridor", "Неправильный номер предприятия");
        ObjectsRusNames.Add("c_falsenumber_tr", "Неправильный номер предприятия ");
        ObjectsRusNames.Add("businessNumberObliqueKoridor", "Неправильный номер предприятия  ");
        ObjectsRusNames.Add("c_falsenum_tn", "Неправильный номер предприятия   ");
        ObjectsRusNames.Add("dirtyFilter", "Грязный фильтр");
        ObjectsRusNames.Add("noWater", "Отсутствует вода");
        ObjectsRusNames.Add("noWaterCommingIn", "Не поступает вода");
        ObjectsRusNames.Add("blindsNonFixedCoupe9", "Автоштора не фиксируется ");
        ObjectsRusNames.Add("blindsNonFixedCoupe2", "Автоштора не фиксируется  ");
        ObjectsRusNames.Add("blindsNonFixedCoupeSleep", "Автоштора не фиксируется   ");
        ObjectsRusNames.Add("blindsNonFixedCoupeOfficial", "Автоштора не фиксируется    ");
        ObjectsRusNames.Add("blindsFasteningCoupeOfficial", "Неисправно крепление автошторы ");
        ObjectsRusNames.Add("blindsFasteningCoupeSleep", "Неисправно крепление автошторы  ");
        ObjectsRusNames.Add("blindsFasteningCoupe2", "Неисправно крепление автошторы   ");
        ObjectsRusNames.Add("blindsFasteningCoupe9", "Неисправно крепление автошторы    ");
        ObjectsRusNames.Add("ladderBrokenCoupe9", "Сломана лестница ");
        ObjectsRusNames.Add("ladderBrokenCoupeSleep", "Сломана лестница  ");
        ObjectsRusNames.Add("c_inventorydoor_off_tn", "Отсутствие инвентаря");
        ObjectsRusNames.Add("fireSafetySystem", "Ложно срабатывает система ПБ");
        ObjectsRusNames.Add("fireSafetySystemButton", "Не включается лампочка - Готов");
        ObjectsRusNames.Add("tumblerBroken", "Излом тумблера сенсорной панели");
        ObjectsRusNames.Add("brokenBoxKoridor", "Сломаны петли ящика для белья");





        ObjectsRusNames.Add("Kotel", "Котловое отделение");
        ObjectsRusNames.Add("VestibuleWorking", "Рабочий тамбур");
        ObjectsRusNames.Add("WC", "Санитарный узел");
        ObjectsRusNames.Add("Koridor", "Коридор");
        ObjectsRusNames.Add("SmallKoridor", "Малый коридор");
        ObjectsRusNames.Add("ObliqueKoridor", "Косой коридор");
        ObjectsRusNames.Add("CoupeSleep", "Купе проводника(отдыха)");
        ObjectsRusNames.Add("CoupeOfficial", "Купе проводника(служебное)");     
        ObjectsRusNames.Add("VestibuleNonWorking", "Тамбур нерабочий");
        ObjectsRusNames.Add("WagonOutside", "Вагон снаружи");
        ObjectsRusNames.Add("None", "Выбранные неисправности:");
        ObjectsRusNames.Add("CoupeNumber9", "Купе № 9");
        ObjectsRusNames.Add("CoupeNumber2", "Купе № 2");
        ObjectsRusNames.Add("WC2", "Санитарный узел №2");
    }
}
